package com.example.albionmarketv2

enum class BuildCategory(val displayName: String, val icon: String) {
    DAMAGE("Maximaler Schaden (DPS)", "⚔️"),
    HEALING("Maximale Heilung (Heal)", "🩺"),
    DEFENSE("Maximale Verteidigung (Tank)", "🛡️"),
    FARMING("Farming & PvE Solo", "🌾"),
    PVP("PvP & Corrupted Dungeons", "🗡️")
}

data class EquipmentBuild(
    val id: String,
    val title: String,
    val category: BuildCategory,
    val tierRecommended: Int = 8,
    val weapon: String,
    val head: String,
    val armor: String,
    val shoes: String,
    val offhand: String = "",
    val cape: String = "Lymhurst-Umhang",
    val food: String = "Rinderbraten T8",
    val potion: String = "Trank des Riesen T7",
    val mount: String = "Panther",
    val damageRating: Int = 50,
    val healingRating: Int = 50,
    val defenseRating: Int = 50,
    val mobilityRating: Int = 50,
    val estimatedCostSilver: Long = 1000000L,
    val aiEvaluationDe: String = "",
    val combatRotationDe: String = "",
    val vorteileDe: List<String> = emptyList(),
    val nachteileDe: List<String> = emptyList()
)

object EquipmentBuildRepository {

    val builds: List<EquipmentBuild> = listOf(
        // ----------------------------------------------------
        // 1. MAXIMALER SCHADEN (DPS) - 5 ELITE BUILDS
        // ----------------------------------------------------
        EquipmentBuild(
            id = "dps_1",
            title = "🔥 One-Shot Curse / Schattensucher",
            category = BuildCategory.DAMAGE,
            tierRecommended = 8,
            weapon = "T8 Schattensucher (Shadowcaller)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Klerikerrobe",
            shoes = "T8 königliche Schuhe",
            offhand = "T8 Nebelrufer",
            cape = "Caerleon-Umhang",
            food = "Schweinesteak T8.1",
            potion = "Gifttrank T8",
            mount = "Panther",
            damageRating = 100,
            healingRating = 10,
            defenseRating = 35,
            mobilityRating = 65,
            estimatedCostSilver = 2100000L,
            aiEvaluationDe = "Tödlichste Burst-Schadensspitze im 1v1 PvP. Löscht Gegner innerhalb von 2 Sekunden aus.",
            combatRotationDe = "1. Fluch Qx3 -> 2. Pirscher-Kapuze -> 3. Klerikerrobe -> 4. E-Todesfluch (4.000+ One-Shot Burst)",
            vorteileDe = listOf("Extremer Instant-Burst", "Unparrierbarer E-Schaden", "Starker Caerleon-Reset"),
            nachteileDe = listOf("Geringe eigene Rüstung", "Anfällig für Purge-Effekte")
        ),
        EquipmentBuild(
            id = "dps_2",
            title = "xe Reichespaltung / Realmbreaker ZvZ",
            category = BuildCategory.DAMAGE,
            tierRecommended = 8,
            weapon = "T8 Reichespaltung (Realmbreaker)",
            head = "T8 Kapuze des Hellion",
            armor = "T8 Söldnerjacke",
            shoes = "T8 Jägerschuhe",
            offhand = "",
            cape = "Fort Sterling-Umhang",
            food = "Rinderbraten T8",
            potion = "Heiltrank T8",
            mount = "Transportochs T8",
            damageRating = 98,
            healingRating = 45,
            defenseRating = 65,
            mobilityRating = 70,
            estimatedCostSilver = 2400000L,
            aiEvaluationDe = "Höchster Flächenschaden (AoE) im ZvZ. Reduziert max. gegnerische HP um 15%.",
            combatRotationDe = "1. Jägersprint -> 2. E-Axtsturz in den Gegner-Blob -> 3. Söldnerblutrausch für Lifesteal",
            vorteileDe = listOf("Massen-AoE HP-Reduktion", "Massive Lifesteal-Synergie", "Sehr hoher ZvZ Impact"),
            nachteileDe = listOf("Hohe Silberkosten", "Abhängig von Treffer der E-Fähigkeit")
        ),
        EquipmentBuild(
            id = "dps_3",
            title = "☄️ Höllenfeuer-Stab / Brimstone Burst",
            category = BuildCategory.DAMAGE,
            tierRecommended = 8,
            weapon = "T8 Schwefelstab (Brimstone Staff)",
            head = "T8 Gelehrtenkapuze",
            armor = "T8 Magierrobe",
            shoes = "T8 königliche Schuhe",
            offhand = "",
            cape = "Bridgewatch-Umhang",
            food = "Omelett T7.1",
            potion = "Gifttrank T8",
            mount = "Panther",
            damageRating = 99,
            healingRating = 0,
            defenseRating = 30,
            mobilityRating = 50,
            estimatedCostSilver = 1950000L,
            aiEvaluationDe = "Verheerendster Meteoritenschaden in ZvZ-Claps. Ein Treffer vernichtet halbe Armeen.",
            combatRotationDe = "1. Gelehrten-Mana aktivieren -> 2. Königssprint -> 3. E-Meteorit mitten in gefesselte Gegner",
            vorteileDe = listOf("Höchster Barm-Schaden im Spiel", "Perfekt für Shotcaller Claps", "Riesige Reichweite"),
            nachteileDe = listOf("Lange Zauberzeit", "Sehr anfällig für Crowd Control")
        ),
        EquipmentBuild(
            id = "dps_4",
            title = "🏹 Armbrust-Scharfschütze / Siegebow",
            category = BuildCategory.DAMAGE,
            tierRecommended = 8,
            weapon = "T8 Belagerungsarmbrust (Siegebow)",
            head = "T8 Ritterhelm",
            armor = "T8 Klerikerrobe",
            shoes = "T8 Soldatenschuhe",
            offhand = "",
            cape = "Thetford-Umhang",
            food = "Rinderbraten T8",
            potion = "Trank des Riesen T8",
            mount = "Pferde-Reittier",
            damageRating = 95,
            healingRating = 0,
            defenseRating = 55,
            mobilityRating = 45,
            estimatedCostSilver = 1800000L,
            aiEvaluationDe = "Stärkster Rüstungsdurchdringungs-Kanalisationsschaden gegen feindliche ZvZ-Frontlines.",
            combatRotationDe = "1. Ritterhelm (CC-Immunität) -> 2. Klerikerschild -> 3. E-Kanalisation für durchbohrenden Flächenschaden",
            vorteileDe = listOf("Durchbricht Rüstungen", "CC-Immunität während Channeling", "Sicher aus der Distanz"),
            nachteileDe = listOf("Immobil während Kanalisierung", "Zielwechsel unterbricht E")
        ),
        EquipmentBuild(
            id = "dps_5",
            title = "🗡️ Dolchpaar Assassin / Dagger Pair",
            category = BuildCategory.DAMAGE,
            tierRecommended = 8,
            weapon = "T8 Dolchpaar (Dagger Pair)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Assassinenjacke",
            shoes = "T8 Jägerschuhe",
            offhand = "",
            cape = "Caerleon-Umhang",
            food = "Schweinesteak T8.1",
            potion = "Gifttrank T8",
            mount = "Panther",
            damageRating = 97,
            healingRating = 10,
            defenseRating = 40,
            mobilityRating = 85,
            estimatedCostSilver = 1650000L,
            aiEvaluationDe = "Gezielter Einzelziel-Meuchelmörder. Exekutiert Schlüsselziele & Heiler im Nu.",
            combatRotationDe = "1. Q-Assassin-Stacks x3 -> 2. Unsichtbarkeit -> 3. Pirscher-Kapuze -> 4. E-Todesstoß",
            vorteileDe = listOf("Exzellentes Ganking", "Hohe Unsichtbarkeits-Mobilität", "Instanter Heiler-Killer"),
            nachteileDe = listOf("Schwer gegen mehrere Gegner", "Kein Flächenschaden")
        ),

        // ----------------------------------------------------
        // 2. MAXIMALE HEILUNG (HEAL) - 5 ELITE BUILDS
        // ----------------------------------------------------
        EquipmentBuild(
            id = "heal_1",
            title = "🩺 Gefallener Stab / Fallen Staff Raid",
            category = BuildCategory.HEALING,
            tierRecommended = 8,
            weapon = "T8 Stab des Gefallenen (Fallen Staff)",
            head = "T8 Klerikerkapuze",
            armor = "T8 Klerikerrobe",
            shoes = "T8 Gelehrtenschuhe",
            offhand = "",
            cape = "Lymhurst-Umhang",
            food = "Omelett T7.1",
            potion = "Energietrank T8",
            mount = "Gepanzerte Schildkröte",
            damageRating = 5,
            healingRating = 100,
            defenseRating = 70,
            mobilityRating = 55,
            estimatedCostSilver = 1900000L,
            aiEvaluationDe = "Unübertroffene Raidheilung. Ein E-Zauber heilt bis zu 10 Verbündete um 80% HP.",
            combatRotationDe = "1. Q-Heilkuppel platzieren -> 2. Bei Raid-Engage E-Erhabene Sanftmut zünden -> 3. Eisblock bei Fokus",
            vorteileDe = listOf("Massiver Gruppen-Instant-Heal", "Reinigt CC-Debuffs", "Sehr hohe Mana-Effizienz"),
            nachteileDe = listOf("Lange E-Abklingzeit", "Geringe Eigenmobilität")
        ),
        EquipmentBuild(
            id = "heal_2",
            title = "⛪ Großes Heiliges Zepter / Great Holy Priest",
            category = BuildCategory.HEALING,
            tierRecommended = 8,
            weapon = "T8 Großes Heiliges Zepter (Great Holy Staff)",
            head = "T8 Söldnerkapuze",
            armor = "T8 Klerikerrobe",
            shoes = "T8 Gelehrtenschuhe",
            offhand = "",
            cape = "Lymhurst-Umhang",
            food = "Omelett T7.1",
            potion = "Energietrank T8",
            mount = "Grizzlybär",
            damageRating = 10,
            healingRating = 98,
            defenseRating = 75,
            mobilityRating = 60,
            estimatedCostSilver = 1550000L,
            aiEvaluationDe = "Bester 5v5 & Hellgate Heiler. Erzeugt ein schützendes Knockback-Heilfeld.",
            combatRotationDe = "1. Einzelheilung Q -> 2. E-Knockback Feld zünden um Taucher zurückzustoßen & Instant-Heal",
            vorteileDe = listOf("Unterbricht gegnerische Engages", "Sehr starke Einziel-Heilung", "Knockback-Schutz"),
            nachteileDe = listOf("E-Bereich begrenzt", "Erfordert gutes Positionierungswissen")
        ),
        EquipmentBuild(
            id = "heal_3",
            title = "🌿 Wildstab Naturheiler / Wild Staff",
            category = BuildCategory.HEALING,
            tierRecommended = 8,
            weapon = "T8 Wilder Naturstab (Wild Staff)",
            head = "T8 Klerikerkapuze",
            armor = "T8 Söldnerjacke",
            shoes = "T8 Soldatenschuhe",
            offhand = "",
            cape = "Lymhurst-Umhang",
            food = "Schweinebraten T8",
            potion = "Heiltrank T8",
            mount = "Panther",
            damageRating = 15,
            healingRating = 96,
            defenseRating = 80,
            mobilityRating = 70,
            estimatedCostSilver = 1700000L,
            aiEvaluationDe = "Kontinuierlicher HoT (Healing over Time) Flächenheiler für mobile Kämpfe.",
            combatRotationDe = "1. Q-Blütenstapel x3 auf Gruppe -> 2. W-Schutzfeld -> 3. E-Riesige Heilwelle aktivieren",
            vorteileDe = listOf("Kontinuierliche Gruppen-Regeneration", "Unempfindlich gegen Unterbrechungen", "Sehr zäh"),
            nachteileDe = listOf("Keine Instant-Single-Burst Heilung", "Stapel können gepurgt werden")
        ),
        EquipmentBuild(
            id = "heal_4",
            title = "✨ Brecilien-Heiliger / Hallowfall Brawler",
            category = BuildCategory.HEALING,
            tierRecommended = 8,
            weapon = "T8 Heiligenschein-Stab (Hallowfall)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Klerikerrobe",
            shoes = "T8 königliche Schuhe",
            offhand = "T8 Nebelrufer",
            cape = "Lymhurst-Umhang",
            food = "Omelett T7.1",
            potion = "Energietrank T8",
            mount = "Panther",
            damageRating = 20,
            healingRating = 97,
            defenseRating = 70,
            mobilityRating = 90,
            estimatedCostSilver = 2800000L,
            aiEvaluationDe = "Höchstmögliche Mobilität aller Heiler. Springt in Verbündete & stößt Gegner hoch.",
            combatRotationDe = "1. E-Sprungheilung direkt auf fokussierten Tank -> 2. Knockup der Gegner nutzen -> 3. Q-Heilung",
            vorteileDe = listOf("Extrem hohe Mobilität & Sprung", "E-Sprung stößt Gegner hoch", "Sehr stark im Small-Scale"),
            nachteileDe = listOf("Sehr teures Artefakt", "Erfordert präzises Timing")
        ),
        EquipmentBuild(
            id = "heal_5",
            title = "🌱 Wucherstab ZvZ / Rampant Staff",
            category = BuildCategory.HEALING,
            tierRecommended = 8,
            weapon = "T8 Wuchernder Naturstab (Rampant Staff)",
            head = "T8 Klerikerkapuze",
            armor = "T8 Klerikerrobe",
            shoes = "T8 Gelehrtenschuhe",
            offhand = "",
            cape = "Lymhurst-Umhang",
            food = "Omelett T7.1",
            potion = "Energietrank T8",
            mount = "Gepanzerter Bär",
            damageRating = 10,
            healingRating = 99,
            defenseRating = 65,
            mobilityRating = 50,
            estimatedCostSilver = 2300000L,
            aiEvaluationDe = "Skaliert mit der Gruppenanzahl. Je mehr Verbündete im Pfad stehen, desto höher die Heilung.",
            combatRotationDe = "1. Q-Stapel auf Frontline halten -> 2. E-Wuchernder Rankenpfad durch die gesamte Armee legen",
            vorteileDe = listOf("Gigantische Flächenheilung im ZvZ", "Skaliert mit Spielerzahl", "Lange Wirkungsdauer"),
            nachteileDe = listOf("Stationärer Heilungspfad", "Lange Abklingzeit")
        ),

        // ----------------------------------------------------
        // 3. MAXIMALE DEFENSE (TANK) - 5 ELITE BUILDS
        // ----------------------------------------------------
        EquipmentBuild(
            id = "def_1",
            title = "🛡️ Schwerer Streitkolben / Heavy Mace Unstoppable",
            category = BuildCategory.DEFENSE,
            tierRecommended = 8,
            weapon = "T8 Schwerer Streitkolben (Heavy Mace)",
            head = "T8 Wächterhelm",
            armor = "T8 Wächterrüstung",
            shoes = "T8 Soldatenschuhe",
            offhand = "",
            cape = "Martlock-Umhang",
            food = "Schweinebraten T8",
            potion = "Trank des Riesen T8",
            mount = "Grizzlybär",
            damageRating = 20,
            healingRating = 15,
            defenseRating = 100,
            mobilityRating = 70,
            estimatedCostSilver = 2400000L,
            aiEvaluationDe = "Absolutes Silence- & Peel-Monster. Bricht feindliche Engages komplett ab.",
            combatRotationDe = "1. Soldatensprint -> 2. E-Silence Ring auf Feindgruppe -> 3. Wächterfeld für 60% Schadensminderung",
            vorteileDe = listOf("Breiter Silence-Ring (Stummschaltung)", "Gegenstände purgen gegnerische Buffs", "Unzerstörbarer Shield"),
            nachteileDe = listOf("Sehr geringer Eigenschaden", "Abhängig von DPS-Followup")
        ),
        EquipmentBuild(
            id = "def_2",
            title = "⚖️ Richter-Rüstung / Judicator Heavy Tank",
            category = BuildCategory.DEFENSE,
            tierRecommended = 8,
            weapon = "T8 Nockenschatten-Streitkolben (Camlann)",
            head = "T8 Richterhelm",
            armor = "T8 Richterrüstung",
            shoes = "T8 Soldatenschuhe",
            offhand = "",
            cape = "Martlock-Umhang",
            food = "Schweinebraten T8",
            potion = "Trank des Riesen T8",
            mount = "Gepanzerte Schildkröte",
            damageRating = 25,
            healingRating = 20,
            defenseRating = 99,
            mobilityRating = 60,
            estimatedCostSilver = 2900000L,
            aiEvaluationDe = "Zieht alle Feinde an einem Punkt zusammen (Vacuum Clap Tank). Bietet der Gruppe Judicator-Aura.",
            combatRotationDe = "1. Sprint -> 2. E-Camlann Vakuum werfen -> 3. Richterrüstung-Schildkuppel für Gruppe zünden",
            vorteileDe = listOf("Zieht Feinde perfekt für Claps zusammen", "Judicator Shield schützt 10+ Spieler", "Sehr hohe CC-Dauer"),
            nachteileDe = listOf("Sehr hoher Preis", "Verlangt schnelles Timing")
        ),
        EquipmentBuild(
            id = "def_3",
            title = "🔱 Inkubus-Keule Raid Tank / Incubus Mace",
            category = BuildCategory.DEFENSE,
            tierRecommended = 8,
            weapon = "T8 Inkubus-Keule (Incubus Mace)",
            head = "T8 Wächterhelm",
            armor = "T8 Rüstung des königlichen Nichtsnutz",
            shoes = "T8 Soldatenschuhe",
            offhand = "T8 Schild der Aegis",
            cape = "Martlock-Umhang",
            food = "Schweinebraten T8",
            potion = "Trank des Riesen T8",
            mount = "Ochs T8",
            damageRating = 30,
            healingRating = 10,
            defenseRating = 97,
            mobilityRating = 65,
            estimatedCostSilver = 2100000L,
            aiEvaluationDe = "Bester Boss- & Raid-Tank im PvE. Reduziert Boss-Schaden und Boss-Schrumpfung um 50%.",
            combatRotationDe = "1. Boss-Aggro halten -> 2. E-Schrumpfkeule werfen -> 3. Wächter-Healdebuff auf heillose Mobs",
            vorteileDe = listOf("Reduziert Boss-Max-HP & Schaden", "Stärkste Aggro-Kontrolle", "Schild-Blockwerte"),
            nachteileDe = listOf("Mäßig im Open-World Solo-PvP", "Reiner Gruppen-PVE Tank")
        ),
        EquipmentBuild(
            id = "def_4",
            title = "🔨 Stangenhammer CC / Polehammer Stunner",
            category = BuildCategory.DEFENSE,
            tierRecommended = 8,
            weapon = "T8 Stangenhammer (Polehammer)",
            head = "T8 Ritterhelm",
            armor = "T8 Ritterrüstung",
            shoes = "T8 Jägerschuhe",
            offhand = "",
            cape = "Fort Sterling-Umhang",
            food = "Schweinebraten T8",
            potion = "Trank des Riesen T8",
            mount = "Grizzlybär",
            damageRating = 35,
            healingRating = 5,
            defenseRating = 94,
            mobilityRating = 75,
            estimatedCostSilver = 1600000L,
            aiEvaluationDe = "Langstrecken Stun-Tank für kleine Gruppen & Arenen. Betäubt Ziele aus sicherer Distanz.",
            combatRotationDe = "1. Ritter-CC-Immunität -> 2. E-Hammerstoß aus Distanz für 3.5s Betäubung -> 3. Rittermauer",
            vorteileDe = listOf("Sicherer Fernkampf-Stun", "Rittermauer blockt feindliche Runs", "Gute Reichweite"),
            nachteileDe = listOf("Weniger AoE-Flächenschutz als Streitkolben", "Kein Vakuum-Pull")
        ),
        EquipmentBuild(
            id = "def_5",
            title = "🛡️ Grauer Wächter / Grovekeeper Hammer",
            category = BuildCategory.DEFENSE,
            tierRecommended = 8,
            weapon = "T8 Hainhüter-Hammer (Grovekeeper)",
            head = "T8 Richterhelm",
            armor = "T8 Wächterrüstung",
            shoes = "T8 Soldatenschuhe",
            offhand = "",
            cape = "Martlock-Umhang",
            food = "Schweinebraten T8",
            potion = "Trank des Riesen T8",
            mount = "Gepanzerte Schildkröte",
            damageRating = 40,
            healingRating = 0,
            defenseRating = 98,
            mobilityRating = 80,
            estimatedCostSilver = 2600000L,
            aiEvaluationDe = "Mächtigster Engagement Stun-Hammer im ZvZ. Springt in den Gegner-Blob und betäubt alle Mobs.",
            combatRotationDe = "1. Soldatensprint -> 2. E-Erdbeben-Sprung mitten in den Gegnerschwarm -> 3. Wächter-Aura",
            vorteileDe = listOf("Riesiger AoE-Sprungstun", "Unterbricht Zauberfeuer", "Massive Rüstung"),
            nachteileDe = listOf("Hohe Silberkosten", "Abhängig vom Followup der DPS")
        ),

        // ----------------------------------------------------
        // 4. FARMING & PVE SOLO - 5 ELITE BUILDS
        // ----------------------------------------------------
        EquipmentBuild(
            id = "farm_1",
            title = "🌾 Naturstab-Metzler / Bramblethorn Solo",
            category = BuildCategory.FARMING,
            tierRecommended = 8,
            weapon = "T8 Dornen-Naturstab (Nature Staff)",
            head = "T8 Kapuze des Gelehrten",
            armor = "T8 Söldnerjacke",
            shoes = "T8 Soldatenschuhe",
            offhand = "T8 Nebelrufer",
            cape = "Thetford-Umhang",
            food = "Rinderbraten T8",
            potion = "Gifttrank T8",
            mount = "Transportochs T8",
            damageRating = 85,
            healingRating = 90,
            defenseRating = 80,
            mobilityRating = 65,
            estimatedCostSilver = 1450000L,
            aiEvaluationDe = "Schnellster Dungeon-Clearspeed & Mobs Farming. Zieht beliebig viele Mobs ohne Sterberisiko.",
            combatRotationDe = "1. Mobs zusammenziehen -> 2. Dornen-Q -> 3. E-Blütenexplosion -> 4. Söldnerblutrausch",
            vorteileDe = listOf("Unendliche Selbstheilung", "Extrem günstiges Equipment", "Zieht riesige Mob-Gruppen"),
            nachteileDe = listOf("Mäßiges PvP-Potential", "Langsame Bewegung ohne Sprint")
        ),
        EquipmentBuild(
            id = "farm_2",
            title = "🔮 Schattensucher Solo Dungeon / Shadowcaller",
            category = BuildCategory.FARMING,
            tierRecommended = 8,
            weapon = "T8 Schattensucher (Shadowcaller)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Hellion-Jacke",
            shoes = "T8 königliche Schuhe",
            offhand = "T8 Cryptcandle",
            cape = "Caerleon-Umhang",
            food = "Rinderbraten T8",
            potion = "Gifttrank T8",
            mount = "Panther",
            damageRating = 98,
            healingRating = 80,
            defenseRating = 60,
            mobilityRating = 75,
            estimatedCostSilver = 3100000L,
            aiEvaluationDe = "Der absolute High-End Solo T8.3 Static & Group Dungeon Solo Clearer.",
            combatRotationDe = "1. Mobs sammeln -> 2. E-Aura auf sich selbst werfen (Lifesteal-Aura) -> 3. Hellion-Jacke zünden",
            vorteileDe = listOf("Schafft T8 Gruppen-Dungeons Solo", "Riesiger AoE-Schaden", "Starker Lifesteal"),
            nachteileDe = listOf("Extrem hohe Ausrüstungskosten", "Hoher Verlust bei Toter in PvP-Zonen")
        ),
        EquipmentBuild(
            id = "farm_3",
            title = "xe Großaxt Speedfarm / Greataxe Rush",
            category = BuildCategory.FARMING,
            tierRecommended = 8,
            weapon = "T8 Großaxt (Greataxe)",
            head = "T8 Kapuze des Gelehrten",
            armor = "T8 Söldnerjacke",
            shoes = "T8 königliche Schuhe",
            offhand = "",
            cape = "Thetford-Umhang",
            food = "Rinderbraten T8",
            potion = "Gifttrank T8",
            mount = "Transportochs T8",
            damageRating = 90,
            healingRating = 70,
            defenseRating = 65,
            mobilityRating = 80,
            estimatedCostSilver = 1250000L,
            aiEvaluationDe = "Einsteigerfreundlichster & schnellster Roving Mobs & Open World Speed-Farmer.",
            combatRotationDe = "1. Q-Axt-Slashes -> 2. E-Wirbelwind aktivieren -> 3. Gelehrten-Kapuze für Mana-Erholung",
            vorteileDe = listOf("Sehr einfaches Handling", "Günstige Anschaffung", "Sehr hoher Wirbel-Schaden"),
            nachteileDe = listOf("Wirbel kann abgebrochen werden", "E-Wirbel gibt Mana-Verbrauch")
        ),
        EquipmentBuild(
            id = "farm_4",
            title = "🏹 Leichte Armbrust / Light Crossbow Clear",
            category = BuildCategory.FARMING,
            tierRecommended = 8,
            weapon = "T8 Leichte Armbrust (Light Crossbow)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Klerikerrobe",
            shoes = "T8 Gelehrtenschuhe",
            offhand = "T8 Nebelrufer",
            cape = "Thetford-Umhang",
            food = "Eintopf T8.1",
            potion = "Gifttrank T8",
            mount = "Pferde-Reittier",
            damageRating = 94,
            healingRating = 20,
            defenseRating = 50,
            mobilityRating = 60,
            estimatedCostSilver = 1100000L,
            aiEvaluationDe = "Sehr hohes Spam-Schadenspotential durch Q-Reset-Passive gegen Boss-Mobs.",
            combatRotationDe = "1. Q-Schuss -> 2. E-Explosivbolzen -> 3. Q-Spam für Dauer-Explosionen",
            vorteileDe = listOf("Höchster Single-Target PvE Boss Schaden", "Günstiges Einsteiger-Setup", "Schneller Mana-Reg"),
            nachteileDe = listOf("Wenig eigener Lifesteal", "Erfordert Kiting bei schweren Mobs")
        ),
        EquipmentBuild(
            id = "farm_5",
            title = "🥊 Stachelhandschuhe / Spiked Gauntlets",
            category = BuildCategory.FARMING,
            tierRecommended = 8,
            weapon = "T8 Stachelhandschuhe (Spiked Gauntlets)",
            head = "T8 Gelehrtenkapuze",
            armor = "T8 Klerikerrobe",
            shoes = "T8 Soldatenschuhe",
            offhand = "",
            cape = "Thetford-Umhang",
            food = "Rinderbraten T8",
            potion = "Gifttrank T8",
            mount = "Panther",
            damageRating = 96,
            healingRating = 10,
            defenseRating = 55,
            mobilityRating = 85,
            estimatedCostSilver = 1500000L,
            aiEvaluationDe = "Löscht Stoff- & Platten-Mobs mit einem einzigen E-Bodenschlag instant aus.",
            combatRotationDe = "1. Mobs in Linie ziehen -> 2. E-Stachelschlag ausführen -> Mobs sofort tot!",
            vorteileDe = listOf("Instanter One-Shot gegen Platten-Mobs", "Sehr hohe Mobilität", "Perfekt für Open World Mobs"),
            nachteileDe = listOf("Schlechter Schaden gegen Stoff-Bosse", "Längere E-Abklingzeit")
        ),

        // ----------------------------------------------------
        // 5. PVP & CORRUPTED DUNGEONS - 5 ELITE BUILDS
        // ----------------------------------------------------
        EquipmentBuild(
            id = "pvp_1",
            title = "🗡️ Doppelklingen-Kämpfer / Double Bladed Stun",
            category = BuildCategory.PVP,
            tierRecommended = 8,
            weapon = "T8 Doppelklingenstab (Double Bladed Staff)",
            head = "T8 Kapuze der Pirschers",
            armor = "T8 Hellion-Jacke",
            shoes = "T8 Jägerschuhe",
            offhand = "",
            cape = "Thetford-Umhang",
            food = "Rinderbraten T8",
            potion = "Heiltrank T8",
            mount = "Panther",
            damageRating = 90,
            healingRating = 75,
            defenseRating = 75,
            mobilityRating = 100,
            estimatedCostSilver = 2300000L,
            aiEvaluationDe = "Höchste Mobilität und Crowd Control im 1v1 PvP & Corrupted Dungeons.",
            combatRotationDe = "1. Jägersprint -> 2. E-Bodenstanz Stun -> 3. Q-Wirbel & Hellion-Aura",
            vorteileDe = listOf("100% Mobilität - Kein Entkommen möglich", "Starke Stuns", "Kann Kämpfe beliebig abbrechen"),
            nachteileDe = listOf("Geringerer Grundschaden als Schwerter", "Erfordert gute Stun-Chains")
        ),
        EquipmentBuild(
            id = "pvp_2",
            title = "🏹 Bogen von Badon / Bow of Badon Duelist",
            category = BuildCategory.PVP,
            tierRecommended = 8,
            weapon = "T8 Bogen von Badon (Bow of Badon)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Klerikerrobe",
            shoes = "T8 königliche Schuhe",
            offhand = "",
            cape = "Thetford-Umhang",
            food = "Rinderbraten T8",
            potion = "Heiltrank T8",
            mount = "Panther",
            damageRating = 93,
            healingRating = 30,
            defenseRating = 60,
            mobilityRating = 85,
            estimatedCostSilver = 2700000L,
            aiEvaluationDe = "Erzeugt ein schreckliches Gewitterfeld, das Zauber feindlicher PvP-Gegner unterbricht.",
            combatRotationDe = "1. Kiting mit Frostpfeil -> 2. E-Gewitterpfeil auf Gegner werfen -> 3. Q-Pfeilspam",
            vorteileDe = listOf("Unterbricht Dauerzauber & Heiler", "Sehr hohes Kiting-Potential", "Große Reichweite"),
            nachteileDe = listOf("Teure Waffe", "Anfällig bei Nahkampf-Sticky-Tanks")
        ),
        EquipmentBuild(
            id = "pvp_3",
            title = "🩸 Blutfeile Outlands Ganker / Bloodletter",
            category = BuildCategory.PVP,
            tierRecommended = 8,
            weapon = "T8 Blutfeile (Bloodletter)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Assassinenjacke",
            shoes = "T8 Soldatenschuhe",
            offhand = "T8 Nebelrufer",
            cape = "Undead-Umhang",
            food = "Schweinesteak T8.1",
            potion = "Gifttrank T8",
            mount = "Panther",
            damageRating = 92,
            healingRating = 20,
            defenseRating = 55,
            mobilityRating = 100,
            estimatedCostSilver = 2100000L,
            aiEvaluationDe = "Der unangefochtene Exekutions-König in Albion Online. Tötet Ziele unter 40% HP instant.",
            combatRotationDe = "1. Gegner auf <40% HP bringen -> 2. E-Exekutionsstich für dreifachen Hinrichtungsschaden",
            vorteileDe = listOf("Exekutionsschaden auf geschwächte Ziele", "Beste Flucht- & Gank-Waffe", "Undead Cape Lebensretter"),
            nachteileDe = listOf("Niedriger Schaden bei vollen Gegner-HP", "Lange E-Cooldowns")
        ),
        EquipmentBuild(
            id = "pvp_4",
            title = "xe Kriegsaxt Brawler / Battleaxe Mists",
            category = BuildCategory.PVP,
            tierRecommended = 8,
            weapon = "T8 Kriegsaxt (Battleaxe)",
            head = "T8 Kapuze des Jägers",
            armor = "T8 Söldnerjacke",
            shoes = "T8 Soldatenschuhe",
            offhand = "T8 Nebelrufer",
            cape = "Thetford-Umhang",
            food = "Rinderbraten T8",
            potion = "Heiltrank T8",
            mount = "Panther",
            damageRating = 88,
            healingRating = 85,
            defenseRating = 75,
            mobilityRating = 75,
            estimatedCostSilver = 1500000L,
            aiEvaluationDe = "Unschlagbar im 1v1 Mists Brawling. Bietet extremen Axtwurf-Schaden mit Eigenheilung.",
            combatRotationDe = "1. Q-Bleed Stacks x3 aufladen -> 2. E-Axtwurf 1 (Schaden) -> 3. E-Axtwurf 2 (Selbstheilung)",
            vorteileDe = listOf("Sehr hohe Eigenheilung beim Werfen", "Starker Dauerschaden durch Bleed", "Sehr zäh im 1v1"),
            nachteileDe = listOf("Axtwurf kann ausgewichen werden", "Wenig Crowd Control")
        ),
        EquipmentBuild(
            id = "pvp_5",
            title = "⚔️ Schnitzschwert Duelist / Carving Sword",
            category = BuildCategory.PVP,
            tierRecommended = 8,
            weapon = "T8 Schnitzschwert (Carving Sword)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Feenrobe / Fiend Robe",
            shoes = "T8 königliche Schuhe",
            offhand = "",
            cape = "Thetford-Umhang",
            food = "Rinderbraten T8",
            potion = "Heiltrank T8",
            mount = "Panther",
            damageRating = 95,
            healingRating = 15,
            defenseRating = 60,
            mobilityRating = 90,
            estimatedCostSilver = 2200000L,
            aiEvaluationDe = "Durchbricht gegnerische Rüstungen um 50% und bietet fantastische Dash-Mobilität.",
            combatRotationDe = "1. Q-Heroic Stacks x3 -> 2. E-Durchbohrender Dash -> 3. Fiend-Robe Furcht-Aura",
            vorteileDe = listOf("Reduziert Rüstung um 50%", "Sicherer Dash-Mobility-Escape", "Extrem stark im Small Scale & Duo"),
            nachteileDe = listOf("Geringe eigene Heilung", "Erfordert Heroic Stacks Management")
        )
    )
}
