package com.example.albionmarketv2

enum class BuildCategory(val displayName: String, val icon: String) {
    DAMAGE_DPS("Schaden / DPS (Allround & Meta)", "💥"),
    MELEE_DPS("Nahkampf-Schaden (Krieger/Dolch)", "⚔️"),
    RANGED_DPS("Fernkampf-Schaden (Jäger/Armbrust)", "🏹"),
    MAGIC_DPS("Magie-Schaden (Magier/Fluch)", "🔮"),
    SHAPESHIFTER("Gestaltwandler (Raubtier/Werwolf/Bär)", "🐺"),
    DEFENSE_TANK("Verteidigung & Tank (Schwer)", "🛡️"),
    HEALING_SUPPORT("Heilung & Support (Kleriker)", "🩺")
}

data class EquipmentBuild(
    val id: String,
    val title: String,
    val category: BuildCategory,
    val tierRecommended: Int = 8,
    val weapon: String,
    val strongestWeaponHighlight: String = "",
    val head: String,
    val armor: String,
    val shoes: String,
    val offhand: String = "",
    val cape: String = "Lymhurst-Umhang",
    val food: String = "Rinderbraten T8",
    val potion: String = "Trank des Riesen T7",
    val mount: String = "Panther",
    val useCaseFunction: String = "🎯 Funktion: Teamfight & ZvZ",
    val recommendedSkills: String = "",
    val headSkill: String = "",
    val armorSkill: String = "",
    val shoesSkill: String = "",
    val damageRating: Int = 50,
    val healingRating: Int = 50,
    val defenseRating: Int = 50,
    val mobilityRating: Int = 50,
    val estimatedCostSilver: Long = 1000000L,
    val aiEvaluationDe: String = "",
    val combatRotationDe: String = "",
    val vorteileDe: List<String> = emptyList(),
    val nachteileDe: List<String> = emptyList()
)

object EquipmentBuildRepository {

    val builds: List<EquipmentBuild> = listOf(
        // ----------------------------------------------------
        // 0. SCHADEN / DPS (ALLROUND & META DPS)
        // ----------------------------------------------------
        EquipmentBuild(
            id = "damage_dps_1",
            title = "🏹 Leichte Armbrust / Light Crossbow (Meta DPS)",
            category = BuildCategory.DAMAGE_DPS,
            tierRecommended = 8,
            weapon = "T8.3 Leichte Armbrust (Light Crossbow)",
            strongestWeaponHighlight = "🏆 Stärkste Fernkampf-DPS Waffe für AoE & ZvZ Burst (Light Crossbow T8.3)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Klerikerrobe",
            shoes = "T8 königliche Schuhe",
            offhand = "T8 Fackel",
            cape = "Thetford-Umhang",
            food = "Rinderbraten T8",
            potion = "Gifttrank T8",
            mount = "Panther",
            useCaseFunction = "🎯 Funktion: Open World PvE, Static Dungeons & Small Scale PvP",
            recommendedSkills = "⚔️ Waffe: Q1 (Exploding Bolt) | W2 (Knockback Shot) | E (Sniper Shot) | Passiv: Energetic",
            headSkill = "🪖 Kopf: Mortal Agony (Schadens-Buff)",
            armorSkill = "🥋 Brust: Everlasting Spirit (Kleriker-Unverwundbarkeit)",
            shoesSkill = "🥾 Schuhe: Royal March (Königs-Sprint)",
            damageRating = 100,
            healingRating = 15,
            defenseRating = 50,
            mobilityRating = 75,
            estimatedCostSilver = 2300000L,
            aiEvaluationDe = "Hervorragender Fernkampf-Burstschaden mit extrem schneller Abklingzeit auf Q und verheerendem E-Schuss.",
            combatRotationDe = "1. Q-Schüsse spammen -> 2. Klerikerrobe bei Fokus -> 3. E-Scharfschützenschuss für massiven Burst.",
            vorteileDe = listOf("Extremer Burst-Schaden", "Kurze Q-Abklingzeiten", "Sehr stark im PvE & PvP"),
            nachteileDe = listOf("Stationär beim E-Schuss", "Hoher Manaverbrauch")
        ),
        EquipmentBuild(
            id = "damage_dps_2",
            title = "🔥 Seuchenstab / Blight Staff (Massen-DPS & Sustain)",
            category = BuildCategory.DAMAGE_DPS,
            tierRecommended = 8,
            weapon = "T8.3 Seuchenstab (Blight Staff)",
            strongestWeaponHighlight = "🏆 Stärkste AoE Seuchen-DPS Waffe für ZvZ & Gruppe",
            head = "T8 Kapuze des Hellion",
            armor = "T8 Söldnerjacke",
            shoes = "T8 Jägerschuhe",
            offhand = "",
            cape = "Lymhurst-Umhang",
            food = "Rinderbraten T8",
            potion = "Heiltrank T8",
            mount = "Panther",
            useCaseFunction = "🎯 Funktion: ZvZ Claps, Massen-PvE & Dungeon-Speedclears",
            recommendedSkills = "⚔️ Waffe: Q1 (Cursed Sickle) | W2 (Desecrate) | E (Blight Pestilence)",
            headSkill = "🪖 Kopf: Smokebomb (Rauchbombe)",
            armorSkill = "🥋 Brust: Bloodlust (Söldnerjacke Lifesteal)",
            shoesSkill = "🥾 Schuhe: Rush (Jägerschuhe Sprint)",
            damageRating = 98,
            healingRating = 50,
            defenseRating = 60,
            mobilityRating = 70,
            estimatedCostSilver = 2600000L,
            aiEvaluationDe = "Verteilt tödlichen Seuchenschaden auf Gegnergruppen und kombiniert exzellenten Flächen-DPS mit starkem Lifesteal.",
            combatRotationDe = "1. Q-Fluch stapeln -> 2. E-Seuchenfeld zünden -> 3. Söldner-Blutrausch für massiven Heilungs-Boost.",
            vorteileDe = listOf("Sehr hoher AoE Schaden", "Guter Selbstheilungs-Sustain", "Stark in ZvZ Blobs"),
            nachteileDe = listOf("Schaden baut sich über Zeit auf", "Anfällig für Purge")
        ),
        // ----------------------------------------------------
        // 1. NAHKAMPF-SCHADEN (MELEE DPS / KRIEGER & DOLCH)
        // ----------------------------------------------------
        EquipmentBuild(
            id = "melee_1",
            title = "🔥 Reichespaltung / Realmbreaker (Krieger-Klasse)",
            category = BuildCategory.MELEE_DPS,
            tierRecommended = 8,
            weapon = "T8.3 Reichespaltung (Realmbreaker)",
            strongestWeaponHighlight = "🏆 Stärkste Axt-Nahkampfwaffe für maximalen AoE-Schaden (Realmbreaker T8.3)",
            head = "T8 Kapuze des Hellion",
            armor = "T8 Söldnerjacke",
            shoes = "T8 Jägerschuhe",
            offhand = "",
            cape = "Fort Sterling-Umhang",
            food = "Rinderbraten T8",
            potion = "Heiltrank T8",
            mount = "Panther",
            useCaseFunction = "🎯 Funktion: Teamfight / ZvZ Claps & Large-Scale PvP",
            recommendedSkills = "⚔️ Waffe: Q1 (Rend Strike) | W2 (Adrenaline Boost) | E (Aftershock) | Passiv: Deep Cuts",
            headSkill = "🪖 Kopf: Smokebomb (Rauchbombe für Unsichtbarkeit) | Passiv: Balanced Mind",
            armorSkill = "🥋 Brust: Bloodlust (Blutrausch Lifesteal) | Passiv: Balanced Mind",
            shoesSkill = "🥾 Schuhe: Rush (Jäger-Sprint Tempo & CC) | Passiv: Quick Thinker",
            damageRating = 99,
            healingRating = 45,
            defenseRating = 65,
            mobilityRating = 70,
            estimatedCostSilver = 2400000L,
            aiEvaluationDe = "Stärkstes Nahkampf-Meta-Setup im ZvZ und Small-Scale. Reduziert gegnerische Max-HP um 15%.",
            combatRotationDe = "1. Jägersprint -> 2. E-Axtsturz in den Gegner-Blob -> 3. Söldnerblutrausch für Lifesteal",
            vorteileDe = listOf("Massen-AoE HP-Reduktion", "Massive Lifesteal-Synergie", "Sehr hoher ZvZ Impact"),
            nachteileDe = listOf("Hohe Silberkosten", "Abhängig von Treffer der E-Fähigkeit")
        ),
        EquipmentBuild(
            id = "melee_2",
            title = "🗡️ Dolchpaar Assassin / Dagger Pair (Schurken-Klasse)",
            category = BuildCategory.MELEE_DPS,
            tierRecommended = 8,
            weapon = "T8.3 Dolchpaar (Dagger Pair)",
            strongestWeaponHighlight = "🏆 Stärkste Einzelziel-Meuchelmörder-Waffe im Nahkampf",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Assassinenjacke",
            shoes = "T8 Jägerschuhe",
            offhand = "",
            cape = "Caerleon-Umhang",
            food = "Schweinesteak T8.1",
            potion = "Gifttrank T8",
            mount = "Panther",
            useCaseFunction = "🎯 Funktion: 1v1 PvP, Corrupted Dungeons & Solo Ganking",
            recommendedSkills = "⚔️ Waffe: Q2 (Assassin Spirit) | W1 (Dash) | E (Slit Throat) | Passiv: Aggressive Burst",
            headSkill = "🪖 Kopf: Mortal Agony (Mörderische Agonie Schadens-Buff) | Passiv: Balanced Mind",
            armorSkill = "🥋 Brust: Ambush (Tarnung Unsichtbarkeit & +40% Burst) | Passiv: Balanced Mind",
            shoesSkill = "🥾 Schuhe: Dodge (Ausweichen Rolle mit Unverwundbarkeit)",
            damageRating = 98,
            healingRating = 10,
            defenseRating = 40,
            mobilityRating = 85,
            estimatedCostSilver = 1650000L,
            aiEvaluationDe = "Gezielter Einzelziel-Meuchelmörder. Exekutiert Schlüsselziele & Heiler im Nu.",
            combatRotationDe = "1. Q-Assassin-Stacks x3 -> 2. Unsichtbarkeit -> 3. Pirscher-Kapuze -> 4. E-Todesstoß",
            vorteileDe = listOf("Exzellentes Ganking", "Hohe Unsichtbarkeits-Mobilität", "Instanter Heiler-Killer"),
            nachteileDe = listOf("Schwer gegen mehrere Gegner", "Kein Flächenschaden")
        ),
        EquipmentBuild(
            id = "melee_3",
            title = "⚔️ Schnitzschwert / Carving Sword (Schwert-Klasse)",
            category = BuildCategory.MELEE_DPS,
            tierRecommended = 8,
            weapon = "T8.3 Schnitzschwert (Carving Sword)",
            strongestWeaponHighlight = "🏆 Stärkste Rüstungsdurchdringungs-Nahkampfwaffe (Carving T8.3)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Feenrobe (Fiend Robe)",
            shoes = "T8 königliche Schuhe",
            offhand = "",
            cape = "Thetford-Umhang",
            food = "Rinderbraten T8",
            potion = "Heiltrank T8",
            mount = "Panther",
            useCaseFunction = "🎯 Funktion: Small Scale PvP, Hellgates & Rüstungs-Debuff Support",
            recommendedSkills = "⚔️ Waffe: Q1 (Heroic Cleave) | W2 (Splitting Slash) | E (Fearless Strike)",
            headSkill = "🪖 Kopf: Mortal Agony (Schadens-Buff)",
            armorSkill = "🥋 Brust: Fear Aura (Furcht-Aura stößt Gegner zurück)",
            shoesSkill = "🥾 Schuhe: Royal March (Königs-Sprint mit Tempo-Stacks)",
            damageRating = 96,
            healingRating = 15,
            defenseRating = 60,
            mobilityRating = 90,
            estimatedCostSilver = 2200000L,
            aiEvaluationDe = "Durchbricht gegnerische Rüstungen um 50% und bietet fantastische Dash-Mobilität.",
            combatRotationDe = "1. Q-Heroic Stacks x3 -> 2. E-Durchbohrender Dash -> 3. Fiend-Robe Furcht-Aura",
            vorteileDe = listOf("Reduziert Rüstung um 50%", "Sicherer Dash-Mobility-Escape", "Extrem stark im Small Scale"),
            nachteileDe = listOf("Geringe eigene Heilung", "Erfordert Heroic Stacks Management")
        ),

        // ----------------------------------------------------
        // 2. FERNKAMPF-SCHADEN (RANGED DPS / JÄGER & ARMBRUST)
        // ----------------------------------------------------
        EquipmentBuild(
            id = "ranged_1",
            title = "🏹 Bogen von Badon / Bow of Badon (Bogen-Klasse)",
            category = BuildCategory.RANGED_DPS,
            tierRecommended = 8,
            weapon = "T8.3 Bogen von Badon (Bow of Badon)",
            strongestWeaponHighlight = "🏆 Stärkste Gewitter-Fernkampfwaffe mit CC-Silence (Badon T8.3)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Klerikerrobe",
            shoes = "T8 königliche Schuhe",
            offhand = "",
            cape = "Thetford-Umhang",
            food = "Rinderbraten T8",
            potion = "Heiltrank T8",
            mount = "Panther",
            useCaseFunction = "🎯 Funktion: Open World PvP, Kiting & Silence Control",
            recommendedSkills = "⚔️ Waffe: Q1 (Deadly Shot) | W2 (Frost Shot Kiting) | E (Raging Storm)",
            headSkill = "🪖 Kopf: Mortal Agony (Mörderische Agonie Schadens-Buff)",
            armorSkill = "🥋 Brust: Everlasting Spirit (Kleriker-Unverwundbarkeit)",
            shoesSkill = "🥾 Schuhe: Royal March (Königs-Sprint)",
            damageRating = 97,
            healingRating = 30,
            defenseRating = 60,
            mobilityRating = 85,
            estimatedCostSilver = 2700000L,
            aiEvaluationDe = "Erzeugt ein schreckliches Gewitterfeld, das Zauber feindlicher PvP-Gegner unterbricht.",
            combatRotationDe = "1. Kiting mit Frostpfeil -> 2. E-Gewitterpfeil auf Gegner werfen -> 3. Q-Pfeilspam",
            vorteileDe = listOf("Unterbricht Dauerzauber & Heiler", "Sehr hohes Kiting-Potential", "Große Reichweite"),
            nachteileDe = listOf("Teure Waffe", "Anfällig bei Nahkampf-Sticky-Tanks")
        ),
        EquipmentBuild(
            id = "ranged_2",
            title = "🎯 Belagerungsarmbrust / Siegebow (Armbrust-Klasse)",
            category = BuildCategory.RANGED_DPS,
            tierRecommended = 8,
            weapon = "T8.3 Belagerungsarmbrust (Siegebow)",
            strongestWeaponHighlight = "🏆 Stärkste Fernkampf-Belagerungswaffe gegen Rüstung (Siegebow T8.3)",
            head = "T8 Ritterhelm",
            armor = "T8 Klerikerrobe",
            shoes = "T8 Soldatenschuhe",
            offhand = "",
            cape = "Thetford-Umhang",
            food = "Rinderbraten T8",
            potion = "Trank des Riesen T8",
            mount = "Pferde-Reittier",
            useCaseFunction = "🎯 Funktion: ZvZ Siege, Claps & Belagerung",
            recommendedSkills = "⚔️ Waffe: Q2 (Auto Fire) | W1 (Knockback Shot) | E (Vicious Volley)",
            headSkill = "🪖 Kopf: Unstoppable (Ritterhelm CC-Immunität für Kanalisierung)",
            armorSkill = "🥋 Brust: Everlasting Spirit (Unverwundbarkeits-Schild)",
            shoesSkill = "🥾 Schuhe: Wanderlust (Soldaten-Sprint)",
            damageRating = 98,
            healingRating = 0,
            defenseRating = 55,
            mobilityRating = 45,
            estimatedCostSilver = 1800000L,
            aiEvaluationDe = "Stärkster Rüstungsdurchdringungs-Kanalisationsschaden gegen feindliche ZvZ-Frontlines.",
            combatRotationDe = "1. Ritterhelm (CC-Immunität) -> 2. Klerikerschild -> 3. E-Kanalisation für durchbohrenden Flächenschaden",
            vorteileDe = listOf("Durchbricht Rüstungen", "CC-Immunität während Channeling", "Sicher aus der Distanz"),
            nachteileDe = listOf("Immobil während Kanalisierung", "Zielwechsel unterbricht E")
        ),

        // ----------------------------------------------------
        // 3. MAGIE-SCHADEN (MAGIC DPS / MAGIER & FLUCH)
        // ----------------------------------------------------
        EquipmentBuild(
            id = "magic_1",
            title = "🔮 Schattensucher / Shadowcaller (Fluch-Magier)",
            category = BuildCategory.MAGIC_DPS,
            tierRecommended = 8,
            weapon = "T8.3 Schattensucher (Shadowcaller)",
            strongestWeaponHighlight = "🏆 Stärkste Magie-Waffe für Burst & Lifesteal (Shadowcaller T8.3)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Klerikerrobe",
            shoes = "T8 königliche Schuhe",
            offhand = "T8 Nebelrufer",
            cape = "Caerleon-Umhang",
            food = "Schweinesteak T8.1",
            potion = "Gifttrank T8",
            mount = "Panther",
            useCaseFunction = "🎯 Funktion: Solo PvE Static Dungeons & 1v1 PvP Corrupted",
            recommendedSkills = "⚔️ Waffe: Q1 (Cursed Sickle) | W2 (Desecrate) | E (Inner Shadow)",
            headSkill = "🪖 Kopf: Mortal Agony (Mörderische Agonie Schadens-Buff)",
            armorSkill = "🥋 Brust: Everlasting Spirit (Kleriker-Schild)",
            shoesSkill = "🥾 Schuhe: Royal March (Königs-Sprint)",
            damageRating = 100,
            healingRating = 30,
            defenseRating = 45,
            mobilityRating = 65,
            estimatedCostSilver = 2100000L,
            aiEvaluationDe = "Tödlichste Magie-Schadensspitze im 1v1 PvP & Dungeon Soloing. Massiver Unparrierbarer E-Schaden.",
            combatRotationDe = "1. Fluch Qx3 -> 2. Pirscher-Kapuze -> 3. Klerikerrobe -> 4. E-Innerer Schatten Burst",
            vorteileDe = listOf("Extremer Instant-Burst", "Unparrierbarer E-Schaden", "Starker Caerleon-Reset"),
            nachteileDe = listOf("Geringe eigene Rüstung", "Anfällig für Purge-Effekte")
        ),
        EquipmentBuild(
            id = "magic_2",
            title = "☄️ Schwefelstab Brimstone / Brimstone Staff (Feuer-Magier)",
            category = BuildCategory.MAGIC_DPS,
            tierRecommended = 8,
            weapon = "T8.3 Schwefelstab (Brimstone Staff)",
            strongestWeaponHighlight = "🏆 Stärkste Meteorit-Feuermagiewaffe im ZvZ-Clap (Brimstone T8.3)",
            head = "T8 Gelehrtenkapuze",
            armor = "T8 Magierrobe",
            shoes = "T8 königliche Schuhe",
            offhand = "",
            cape = "Bridgewatch-Umhang",
            food = "Omelett T7.1",
            potion = "Gifttrank T8",
            mount = "Panther",
            useCaseFunction = "🎯 Funktion: ZvZ Shotcaller Claps & Large-Scale AoE",
            recommendedSkills = "⚔️ Waffe: Q1 (Fire Bolt) | W1 (Wall of Flames) | E (Meteor)",
            headSkill = "🪖 Kopf: Energy Shield (Gelehrten-Mana & Defense)",
            armorSkill = "🥋 Brust: Purge Shield / Damage Buff (Magier-Robe)",
            shoesSkill = "🥾 Schuhe: Royal March (Königs-Sprint)",
            damageRating = 100,
            healingRating = 0,
            defenseRating = 30,
            mobilityRating = 50,
            estimatedCostSilver = 1950000L,
            aiEvaluationDe = "Verheerendster Meteoritenschaden in ZvZ-Claps. Ein Treffer vernichtet feindliche Formationen.",
            combatRotationDe = "1. Gelehrten-Mana aktivieren -> 2. Königssprint -> 3. E-Meteorit mitten in gefesselte Gegner",
            vorteileDe = listOf("Höchster Barm-Schaden im Spiel", "Perfekt für Shotcaller Claps", "Riesige Reichweite"),
            nachteileDe = listOf("Lange Zauberzeit", "Sehr anfällig für Crowd Control")
        ),

        // ----------------------------------------------------
        // 4. GESTALTWANDLER (SHAPESHIFTER STAFFS / RAUBTIER & WERWOLF)
        // ----------------------------------------------------
        EquipmentBuild(
            id = "shifter_1",
            title = "🐺 Raubkatzenstab / Prowler Staff (Schatten-Panther)",
            category = BuildCategory.SHAPESHIFTER,
            tierRecommended = 8,
            weapon = "T8.3 Raubkatzenstab (Prowler Staff)",
            strongestWeaponHighlight = "🏆 Stärkste Gestaltwandler-Waffe für Unsichtbarkeit & Execution-Burst (Prowler T8.3)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Assassinenjacke",
            shoes = "T8 königliche Schuhe",
            offhand = "",
            cape = "Caerleon-Umhang",
            food = "Rinderbraten T8",
            potion = "Trank des Riesen T8",
            mount = "Panther",
            useCaseFunction = "🎯 Funktion: 1v1 PvP, Ganking & Single Target Execution",
            recommendedSkills = "⚔️ Waffe: Q1 (Shiftcharge) | W2 (Polymorph Dash) | E (Prowler Form)",
            headSkill = "🪖 Kopf: Mortal Agony (Mörderische Agonie Schadens-Buff)",
            armorSkill = "🥋 Brust: Ambush (Assassinen-Tarnung & +40% Burst)",
            shoesSkill = "🥾 Schuhe: Royal March (Königs-Sprint)",
            damageRating = 100,
            healingRating = 20,
            defenseRating = 50,
            mobilityRating = 95,
            estimatedCostSilver = 3500000L,
            aiEvaluationDe = "Verwandelt den Zauberer in einen Schatten-Panther mit Unsichtbarkeit, Execution-Dash und unparrierbarem Burst-Schaden.",
            combatRotationDe = "1. Q-Shiftcharges sammeln -> 2. E-Panther-Verwandlung -> 3. Prowler Dash Execution -> 4. Unsichtbarkeit Escape",
            vorteileDe = listOf("Garantierte Unsichtbarkeits-Flucht", "Extreme Single-Target Execution", "Sehr hohe Mobilität"),
            nachteileDe = listOf("Sehr teures Gestaltwandler-Artefakt", "Erfordert Aufladen der Ladungen")
        ),
        EquipmentBuild(
            id = "shifter_2",
            title = "🩸 Werwolfstab / Bloodmoon Staff (Blutmond-Werwolf)",
            category = BuildCategory.SHAPESHIFTER,
            tierRecommended = 8,
            weapon = "T8.3 Werwolfstab (Bloodmoon Staff)",
            strongestWeaponHighlight = "🏆 Stärkste Gestaltwandler-Waffe für Lifesteal, Blutrausch & Tanky Melee DPS",
            head = "T8 Kapuze des Hellion",
            armor = "T8 Söldnerjacke",
            shoes = "T8 Jägerschuhe",
            offhand = "",
            cape = "Fort Sterling-Umhang",
            food = "Rinderbraten T8",
            potion = "Heiltrank T8",
            mount = "Direwolf",
            useCaseFunction = "🎯 Funktion: Tanky Melee DPS, Lifesteal & Small Scale PvP",
            recommendedSkills = "⚔️ Waffe: Q1 (Feral Claw) | W1 (Roar) | E (Werewolf Form)",
            headSkill = "🪖 Kopf: Smokebomb (Rauchbombe für Unsichtbarkeit)",
            armorSkill = "🥋 Brust: Bloodlust (Söldnerjacke Lifesteal)",
            shoesSkill = "🥾 Schuhe: Rush (Jägerschuhe Sprint)",
            damageRating = 97,
            healingRating = 65,
            defenseRating = 70,
            mobilityRating = 85,
            estimatedCostSilver = 3200000L,
            aiEvaluationDe = "Transformiert in einen blutrünstigen Werwolf. Gewährt extrem hohen Lebensraub, Flächenklauen und Unaufhaltsamkeit.",
            combatRotationDe = "1. W-Gebrüll für Angriffs-Buff -> 2. E-Werwolf-Verwandlung -> 3. Klauenhiebe in Gegnergruppe für volles HP-Refill",
            vorteileDe = listOf("Immens starker Lifesteal", "Hohe Lebenspunkte & Eigenheilung", "Perfekt für Solo & Small Scale"),
            nachteileDe = listOf("Anfällig für Stun-Ketten", "Hoher Silberpreis")
        ),
        EquipmentBuild(
            id = "shifter_3",
            title = "🐻 Runen-Bärenstab / Earthrune Staff (Urzeit-Bär)",
            category = BuildCategory.SHAPESHIFTER,
            tierRecommended = 8,
            weapon = "T8.3 Runen-Bärenstab (Earthrune Staff)",
            strongestWeaponHighlight = "🏆 Stärkste Gestaltwandler-Waffe für Massen-Stun, CC & Bären-Rüstung",
            head = "T8 Wächterhelm",
            armor = "T8 Wächterrüstung",
            shoes = "T8 Soldatenschuhe",
            offhand = "",
            cape = "Martlock-Umhang",
            food = "Schweinebraten T8",
            potion = "Trank des Riesen T8",
            mount = "Grizzlybär",
            useCaseFunction = "🎯 Funktion: ZvZ Frontline Engage, Massen-Stun & Bären-Tank",
            recommendedSkills = "⚔️ Waffe: Q1 (Earth Smash) | W2 (Heavy Maul) | E (Giant Bear Form)",
            headSkill = "🪖 Kopf: Stone Skin (Wächterhelm Shield)",
            armorSkill = "🥋 Brust: Enfeeble Aura (Wächterrüstung Debuff)",
            shoesSkill = "🥾 Schuhe: Wanderlust (Soldaten-Sprint)",
            damageRating = 65,
            healingRating = 10,
            defenseRating = 98,
            mobilityRating = 70,
            estimatedCostSilver = 3100000L,
            aiEvaluationDe = "Verwandelt den Charakter in einen gigantischen Urzeit-Bären mit enormer Schadensminderung, Schild & Erdbeben-CC.",
            combatRotationDe = "1. E-Bären-Verwandlung -> 2. Bären-Schrei für Schild -> 3. Erdbeben-Stampfer für Massen-Stun",
            vorteileDe = listOf("Riesiger Rüstungs- & Schild-Buff", "AoE Stun & Knockup", "Extrem zäh"),
            nachteileDe = listOf("Geringerer Burst-Schaden als Panther", "Lange Abklingzeiten")
        ),

        // ----------------------------------------------------
        // 5. VERTEIDIGUNG & TANK (SCHWERER TANK / STREITKOLBEN)
        // ----------------------------------------------------
        EquipmentBuild(
            id = "tank_1",
            title = "🛡️ Schwerer Streitkolben / Heavy Mace (Tank-Klasse)",
            category = BuildCategory.DEFENSE_TANK,
            tierRecommended = 8,
            weapon = "T8.3 Schwerer Streitkolben (Heavy Mace)",
            strongestWeaponHighlight = "🏆 Stärkste Tank-Waffe für Silence & Stummschaltung (Heavy Mace T8.3)",
            head = "T8 Wächterhelm",
            armor = "T8 Wächterrüstung",
            shoes = "T8 Soldatenschuhe",
            offhand = "",
            cape = "Martlock-Umhang",
            food = "Schweinebraten T8",
            potion = "Trank des Riesen T8",
            mount = "Grizzlybär",
            useCaseFunction = "🎯 Funktion: ZvZ Frontline Peel & Silence Stummschaltung",
            recommendedSkills = "⚔️ Waffe: Q1 (Threatening Strike) | W2 (Snare Charge) | E (Battle Blast)",
            headSkill = "🪖 Kopf: Stone Skin (Wächterhelm Shield & Heal)",
            armorSkill = "🥋 Brust: Enfeeble Aura (Wächterrüstung -60% Gegner-Schaden)",
            shoesSkill = "🥾 Schuhe: Wanderlust (Soldaten-Sprint)",
            damageRating = 20,
            healingRating = 15,
            defenseRating = 100,
            mobilityRating = 70,
            estimatedCostSilver = 2400000L,
            aiEvaluationDe = "Absolutes Silence- & Peel-Monster. Bricht feindliche Engages komplett ab.",
            combatRotationDe = "1. Soldatensprint -> 2. E-Silence Ring auf Feindgruppe -> 3. Wächterfeld für 60% Schadensminderung",
            vorteileDe = listOf("Breiter Silence-Ring (Stummschaltung)", "Gegenstände purgen gegnerische Buffs", "Unzerstörbarer Shield"),
            nachteileDe = listOf("Sehr geringer Eigenschaden", "Abhängig von DPS-Followup")
        ),
        EquipmentBuild(
            id = "tank_2",
            title = "🔨 Hainhüter-Hammer / Grovekeeper (Hammer-Tank)",
            category = BuildCategory.DEFENSE_TANK,
            tierRecommended = 8,
            weapon = "T8.3 Hainhüter-Hammer (Grovekeeper)",
            strongestWeaponHighlight = "🏆 Stärkste Stun-Engage-Tank-Waffe im ZvZ (Grovekeeper T8.3)",
            head = "T8 Richterhelm",
            armor = "T8 Wächterrüstung",
            shoes = "T8 Soldatenschuhe",
            offhand = "",
            cape = "Martlock-Umhang",
            food = "Schweinebraten T8",
            potion = "Trank des Riesen T8",
            mount = "Gepanzerte Schildkröte",
            useCaseFunction = "🎯 Funktion: ZvZ Stun Engage & Teamfight Frontline",
            recommendedSkills = "⚔️ Waffe: Q1 (Iron Breaker) | W1 (Geyser) | E (Ground Slam Stun Sprung)",
            headSkill = "🪖 Kopf: Judgement (Richter-Helm Stun & Debuff)",
            armorSkill = "🥋 Brust: Enfeeble Aura (Wächterrüstung)",
            shoesSkill = "🥾 Schuhe: Wanderlust (Soldaten-Sprint)",
            damageRating = 40,
            healingRating = 0,
            defenseRating = 98,
            mobilityRating = 80,
            estimatedCostSilver = 2600000L,
            aiEvaluationDe = "Mächtigster Engagement Stun-Hammer im ZvZ. Springt in den Gegner-Blob und betäubt alle Mobs.",
            combatRotationDe = "1. Soldatensprint -> 2. E-Erdbeben-Sprung mitten in den Gegnerschwarm -> 3. Wächter-Aura",
            vorteileDe = listOf("Riesiger AoE-Sprungstun", "Unterbricht Zauberfeuer", "Massive Rüstung"),
            nachteileDe = listOf("Hohe Silberkosten", "Abhängig vom Followup der DPS")
        ),

        // ----------------------------------------------------
        // 6. HEILUNG & SUPPORT (HEILER & KLERIKER)
        // ----------------------------------------------------
        EquipmentBuild(
            id = "heal_1",
            title = "🩺 Stab des Gefallenen / Fallen Staff (Heiliger-Stab)",
            category = BuildCategory.HEALING_SUPPORT,
            tierRecommended = 8,
            weapon = "T8.3 Stab des Gefallenen (Fallen Staff)",
            strongestWeaponHighlight = "🏆 Stärkste Gruppen-Instant-Heilungs-Waffe im Spiel (Fallen Staff T8.3)",
            head = "T8 Klerikerkapuze",
            armor = "T8 Klerikerrobe",
            shoes = "T8 Gelehrtenschuhe",
            offhand = "",
            cape = "Lymhurst-Umhang",
            food = "Omelett T7.1",
            potion = "Energietrank T8",
            mount = "Gepanzerte Schildkröte",
            useCaseFunction = "🎯 Funktion: ZvZ & Raid Gruppen-Massen-Heilung",
            recommendedSkills = "⚔️ Waffe: Q1 (Generous Heal) | W2 (Holy Beam) | E (Salvation Instant-Heal Circle)",
            headSkill = "🪖 Kopf: Ice Block (Klerikerkapuze Unverwundbarkeits-Eisblock)",
            armorSkill = "🥋 Brust: Everlasting Spirit (Kleriker-Schild)",
            shoesSkill = "🥾 Schuhe: Focused Run (Gelehrten-Sprint & Mana-Reg)",
            damageRating = 5,
            healingRating = 100,
            defenseRating = 70,
            mobilityRating = 55,
            estimatedCostSilver = 1900000L,
            aiEvaluationDe = "Unübertroffene Raidheilung. Ein E-Zauber heilt bis zu 10 Verbündete um 80% HP.",
            combatRotationDe = "1. Q-Heilkuppel platzieren -> 2. Bei Raid-Engage E-Erhabene Sanftmut zünden -> 3. Eisblock bei Fokus",
            vorteileDe = listOf("Massiver Gruppen-Instant-Heal", "Reinigt CC-Debuffs", "Sehr hohe Mana-Effizienz"),
            nachteileDe = listOf("Lange E-Abklingzeit", "Geringe Eigenmobilität")
        ),
        EquipmentBuild(
            id = "heal_2",
            title = "✨ Heiligenschein-Stab / Hallowfall (Brecilien-Heiler)",
            category = BuildCategory.HEALING_SUPPORT,
            tierRecommended = 8,
            weapon = "T8.3 Heiligenschein-Stab (Hallowfall)",
            strongestWeaponHighlight = "🏆 Stärkste Sprung-Heilungswaffe mit Mobilität & Knockup (Hallowfall T8.3)",
            head = "T8 Kapuze des Pirschers",
            armor = "T8 Klerikerrobe",
            shoes = "T8 königliche Schuhe",
            offhand = "T8 Nebelrufer",
            cape = "Lymhurst-Umhang",
            food = "Omelett T7.1",
            potion = "Energietrank T8",
            mount = "Panther",
            useCaseFunction = "🎯 Funktion: Small Scale PvP, Hellgates & High-Mobility Group Heal",
            recommendedSkills = "⚔️ Waffe: Q2 (Flash Heal) | W1 (Sacred Pulse) | E (Divine Angel Sprung-Heal)",
            headSkill = "🪖 Kopf: Mortal Agony (Schadens/Heilungs-Buff)",
            armorSkill = "🥋 Brust: Everlasting Spirit (Kleriker-Schild)",
            shoesSkill = "🥾 Schuhe: Royal March (Königs-Sprint)",
            damageRating = 20,
            healingRating = 98,
            defenseRating = 70,
            mobilityRating = 90,
            estimatedCostSilver = 2800000L,
            aiEvaluationDe = "Höchstmögliche Mobilität aller Heiler. Springt in Verbündete & stößt Gegner hoch.",
            combatRotationDe = "1. E-Sprungheilung direkt auf fokussierten Tank -> 2. Knockup der Gegner nutzen -> 3. Q-Heilung",
            vorteileDe = listOf("Extrem hohe Mobilität & Sprung", "E-Sprung stößt Gegner hoch", "Sehr stark im Small-Scale"),
            nachteileDe = listOf("Sehr teures Artefakt", "Erfordert präzises Timing")
        )
    )
}
