package com.example.albionmarketv2

object LanguageManager {

    enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
        DE("DE", "Deutsch", "🇩🇪"),
        EN("EN", "English", "🇬🇧"),
        ES("ES", "Español", "🇪🇸"),
        FR("FR", "Français", "🇫🇷"),
        PT("PT", "Português", "🇵🇹"),
        RU("RU", "Русский", "🇷🇺"),
        ZH("ZH", "中文", "🇨🇳"),
        JA("JA", "日本語", "🇯🇵"),
        KO("KO", "한국어", "🇰🇷"),
        TR("TR", "Türkçe", "🇹🇷"),
        ID("ID", "Bahasa Indonesia", "🇮🇩"),
        PL("PL", "Polski", "🇵🇱")
    }

    private val deMap = mapOf(
        "app_title" to "AlbionDataPro",
        "app_subtitle" to "Echtzeit-Analyse & Trade Alerts",
        "tab_orders" to "📋 Aufträge & Historie",
        "tab_calculator" to "🧮 Rechner & Marge (Top 50)",
        "tab_catalog" to "📖 Markt-Katalog",
        "tab_builds" to "⚔️ KI Ausrüstung & Build-Sets",
        "tab_order_stats" to "📊 Order-Statistik (1T-1J)",
        "tab_events" to "🔥 Events & Boss Loot",
        "tab_gold" to "🪙 Goldmarkt",
        "tab_map" to "🗺️ Albion Weltkarte",
        "server_select" to "Server auswählen:",
        "silver_budget" to "Silber-Budget",
        "carry_capacity" to "Traglast (kg)",
        "min_margin" to "Mindest-Marge (%)",
        "premium_tax" to "Premium 4% Steuer",
        "standard_tax" to "Standard 8% Steuer",
        "avoid_danger" to "Gefährliche Zonen (Caerleon / Rot) meiden",
        "avoid_danger_desc" to "Schließt Caerleon & Full-Loot PvP Zonen aus",
        "top_opportunities" to "Lukrativste Handelschancen",
        "buy_in" to "Einkauf in",
        "sell_in" to "Verkauf in",
        "quantity" to "Menge",
        "weight" to "Gewicht",
        "investment" to "Investition",
        "profit_per_unit" to "Gewinn/Stk",
        "accept_order" to "Auftrag annehmen",
        "gold_buy" to "🪙 Gold Einkauf",
        "gold_sell" to "🪙 Gold Verkauf",
        "settings_title" to "⚙️ Einstellungen & Alerts",
        "bubble_toggle" to "Floating Bubble Overlay",
        "bubble_desc" to "Zeigt eine verschiebbare Bubble permanent über Albion Online an",
        "sys_notif_toggle" to "System Push-Benachrichtigungen",
        "sys_notif_desc" to "Zeigt Android-Alerts bei neuen Top-Deals in Echtzeit an",
        "gold_notif_toggle" to "Gold-Portfolio Benachrichtigungen",
        "gold_notif_desc" to "Zeigt automatische Live-Einnahmen Alerts bei Goldkurs-Updates an",
        "background_btn" to "🔋 App im Hintergrund unbegrenzt ausführen",
        "lang_select" to "Sprache / Language / 语言:",
        "save" to "Speichern",
        "close" to "Schließen",
        "roi" to "Marge",
        "no_price_data" to "Bisher kein Preis",
        
        // Bubble translations
        "bubble_options" to "⚙️ Bubble Optionen",
        "bubble_lang" to "Sprache:",
        "bubble_category" to "Kategorie Filter:",
        "bubble_active_order" to "📦 Aktiver Auftrag",
        "bubble_top_margin" to "🔥 Handelschancen",
        "bubble_max_distance" to "Maximale Distanz (Zonen)",
        "bubble_min_stock" to "Max. Bestand",
        "bubble_max_stock" to "Max. Bestand",
        "bubble_book" to "Buchen",
        "bubble_cancel" to "Stornieren",
        "bubble_abort" to "Abbrechen",
        "bubble_save_book" to "Speichern & Buchen",
        "bubble_location" to "🏙️ Standpunkt:",
        "bubble_all_cities" to "Alle Städte",
        "bubble_all" to "Alle",
        "bubble_click_accept" to "Klicke zum Annehmen",
        "bubble_calculating" to "Berechne Top Marktchancen...",
        "bubble_no_opps" to "Keine passenden Marktchancen gefunden.",
        "bubble_search" to "Marktsuche...",
        "bubble_hold_move" to "Gedrückt halten zum Verschieben",
        "bubble_exit" to "Beenden",
        "bubble_kauf" to "Kauf:",
        "bubble_verkauf" to "Verkauf:",
        "bubble_buy_price" to "Kauf-Stückpreis (Silber)",
        "bubble_sell_price" to "Verkauf-Stückpreis (Silber)",
        "bubble_bought_amount" to "Gekaufte Stückzahl",
        "bubble_spent" to "Ausgegeben",
        "bubble_earned" to "Netto-Umsatz",
        "bubble_profit_loss" to "Gewinn/Verlust",
        "bubble_include_brecilien" to "Brecilien in Routen einschließen",
        "bubble_compact_mode" to "📱 Kompakter Bubble-Modus",
        "bubble_compact_desc" to "Verkleinert Fenster, Abstände und Schriftgrößen der Bubble",
        "bubble_opacity" to "👁️ Bubble-Transparenz / Deckkraft",
        "bubble_scale" to "🔍 Bubble-Skalierung (Größe)",
        "tab_crafting" to "🛠️ Crafting Guide",
        "tab_island" to "🏝️ Insel Guide",
        "tab_monsters" to "👹 Monster & Bosse",
        "crafting_search" to "Item zum Craften suchen...",
        "monster_search" to "Monster, Boss, Region oder Drop suchen...",
        "crafting_req_ingredients" to "Benötigte Ressourcen & günstigster Markt:",
        "cheapest_at" to "Günstigster Einkauf",

        // Cities
        "city_caerleon" to "Caerleon",
        "city_brecilien" to "Brecilien",
        "city_arthurs_rest" to "Arthurs Rast",
        "city_merlyns_rest" to "Merlyns Rast",
        "city_morganas_rest" to "Morganas Rast",
        "city_bridgewatch" to "Bridgewatch",
        "city_martlock" to "Martlock",
        "city_lymhurst" to "Lymhurst",
        "city_fort_sterling" to "Fort Sterling",
        "city_thetford" to "Thetford",
        "city_cairn_drain" to "Cairn Drain",
        "red_zone" to "🔴 ROT-ZONE",
        "black_zone" to "⚫ BLACK-ZONE"
    )

    private val enMap = mapOf(
        "app_title" to "Albion Online Market Resources",
        "app_subtitle" to "Real-time Analytics & Trade Alerts",
        "tab_orders" to "📋 Orders & History",
        "tab_calculator" to "🧮 Calculator & Margin (Top 50)",
        "tab_catalog" to "📖 Market Catalog",
        "tab_builds" to "⚔️ AI Gear & Build Sets",
        "tab_order_stats" to "📊 Order Statistics (1D-1Y)",
        "tab_events" to "🔥 Events & Boss Loot",
        "tab_gold" to "🪙 Gold Market",
        "tab_map" to "🗺️ Albion World Map",
        "server_select" to "Select Server:",
        "silver_budget" to "Silver Budget",
        "carry_capacity" to "Carry Capacity (kg)",
        "min_margin" to "Min Margin (%)",
        "premium_tax" to "Premium 4% Tax",
        "standard_tax" to "Standard 8% Tax",
        "avoid_danger" to "Avoid Dangerous Zones (Caerleon / Red)",
        "avoid_danger_desc" to "Excludes Caerleon & Full-Loot PvP Zones",
        "top_opportunities" to "Most Profitable Trade Deals",
        "buy_in" to "Buy in",
        "sell_in" to "Sell in",
        "quantity" to "Quantity",
        "weight" to "Weight",
        "investment" to "Investment",
        "profit_per_unit" to "Profit/Unit",
        "accept_order" to "Accept & Save Order",
        "gold_buy" to "🪙 Gold Buy",
        "gold_sell" to "🪙 Gold Sell",
        "settings_title" to "⚙️ Settings & Alerts",
        "bubble_toggle" to "Floating Bubble Overlay",
        "bubble_desc" to "Displays a draggable bubble permanently over Albion Online",
        "sys_notif_toggle" to "System Push Notifications",
        "sys_notif_desc" to "Displays Android alerts for top deals in real time",
        "gold_notif_toggle" to "Gold Portfolio Notifications",
        "gold_notif_desc" to "Sends automatic live income alerts on gold price updates",
        "background_btn" to "🔋 Run App Unrestricted in Background",
        "lang_select" to "Language / Sprache / 语言:",
        "save" to "Save",
        "close" to "Close",
        "roi" to "ROI",
        "no_price_data" to "No price yet",

        // Bubble translations
        "bubble_options" to "⚙️ Bubble Settings",
        "bubble_lang" to "Language:",
        "bubble_category" to "Category Filter:",
        "bubble_active_order" to "📦 Active Order",
        "bubble_top_margin" to "🔥 Top 3 Margin",
        "bubble_book" to "Book",
        "bubble_cancel" to "Cancel",
        "bubble_abort" to "Abort",
        "bubble_save_book" to "Save & Book",
        "bubble_location" to "🏙️ Location:",
        "bubble_all_cities" to "All Cities",
        "bubble_all" to "All",
        "bubble_click_accept" to "Click to accept",
        "bubble_calculating" to "Calculating top opportunities...",
        "bubble_no_opps" to "No matching market opportunities found.",
        "bubble_search" to "Market search...",
        "bubble_hold_move" to "Hold to move",
        "bubble_exit" to "Exit",
        "bubble_kauf" to "Buy:",
        "bubble_verkauf" to "Sell:",
        "bubble_buy_price" to "Buy price (Silver)",
        "bubble_sell_price" to "Sell price (Silver)",
        "bubble_bought_amount" to "Bought quantity",
        "bubble_spent" to "Spent",
        "bubble_earned" to "Net Revenue",
        "bubble_profit_loss" to "Profit/Loss",
        "bubble_include_brecilien" to "Include Brecilien in routes",
        "bubble_compact_mode" to "📱 Compact Bubble Mode",
        "bubble_compact_desc" to "Reduces window size, padding, and font size of the bubble",
        "bubble_opacity" to "👁️ Bubble Opacity",
        "bubble_scale" to "🔍 Bubble Scale (Size)",
        "tab_crafting" to "🛠️ Crafting Guide",
        "tab_island" to "🏝️ Island Guide",
        "tab_monsters" to "👹 Monsters & Bosses",
        "crafting_search" to "Search item to craft...",
        "monster_search" to "Search monster, boss, region, or drop...",
        "crafting_req_ingredients" to "Required ingredients & cheapest market:",
        "cheapest_at" to "Cheapest buy",

        // Cities
        "city_caerleon" to "Caerleon",
        "city_brecilien" to "Brecilien",
        "city_arthurs_rest" to "Arthur's Rest",
        "city_merlyns_rest" to "Merlyn's Rest",
        "city_morganas_rest" to "Morgana's Rest",
        "city_bridgewatch" to "Bridgewatch",
        "city_martlock" to "Martlock",
        "city_lymhurst" to "Lymhurst",
        "city_fort_sterling" to "Fort Sterling",
        "city_thetford" to "Thetford",
        "city_cairn_drain" to "Cairn Drain",
        "red_zone" to "🔴 RED ZONE",
        "black_zone" to "⚫ BLACK ZONE"
    )

    private val zhMap = mapOf(
        "app_title" to "阿尔比恩在线 市场资源助手",
        "app_subtitle" to "实时分析 & 交易警报",
        "tab_orders" to "📋 订单与历史",
        "tab_calculator" to "🧮 利润计算器 (前50热门)",
        "tab_catalog" to "📖 市场目录",
        "tab_builds" to "⚔️ AI 装备与套装",
        "tab_order_stats" to "📊 订单与市场统计 (1日-1年)",
        "tab_events" to "🔥 活动与战利品",
        "tab_gold" to "🪙 黄金市场",
        "tab_map" to "🗺️ 阿尔比恩地图",
        "server_select" to "选择服务器:",
        "silver_budget" to "银币预算",
        "carry_capacity" to "负重上限 (kg)",
        "min_margin" to "最低利润率 (%)",
        "premium_tax" to "会员 4% 税率",
        "standard_tax" to "标准 8% 税率",
        "avoid_danger" to "避开危险区域 (卡尔利昂 / 红区)",
        "avoid_danger_desc" to "排除卡尔利昂及全掉落 PvP 区域",
        "top_opportunities" to "最高利润交易机会",
        "buy_in" to "购买地",
        "sell_in" to "出售地",
        "quantity" to "数量",
        "weight" to "重量",
        "investment" to "总投资",
        "profit_per_unit" to "单件利润",
        "accept_order" to "接受并保存订单",
        "gold_buy" to "🪙 黄金买入",
        "gold_sell" to "🪙 黄金卖出",
        "settings_title" to "⚙️ 设置与警报",
        "bubble_toggle" to "悬浮气泡 Overlay",
        "bubble_desc" to "在阿尔比恩游戏上方永久显示可拖动悬浮气泡",
        "sys_notif_toggle" to "系统推送通知",
        "sys_notif_desc" to "实时接收热门交易机会推送",
        "gold_notif_toggle" to "黄金投资组合通知",
        "gold_notif_desc" to "在黄金价格更新时自动发送实时收益警报",
        "background_btn" to "允许后台无限制运行",
        "lang_select" to "语言 / Language / 语言:",
        "save" to "保存",
        "close" to "关闭",
        "roi" to "利润率",
        "no_price_data" to "暂无价格",

        // Bubble translations
        "bubble_options" to "⚙️ 悬浮窗设置",
        "bubble_lang" to "语言:",
        "bubble_category" to "分类过滤:",
        "bubble_active_order" to "📦 当前订单",
        "bubble_top_margin" to "🔥 利润前三",
        "bubble_book" to "记账",
        "bubble_cancel" to "取消订单",
        "bubble_abort" to "取消",
        "bubble_save_book" to "保存并记账",
        "bubble_location" to "🏙️ 位置:",
        "bubble_all_cities" to "所有城市",
        "bubble_all" to "全部",
        "bubble_click_accept" to "点击接受",
        "bubble_calculating" to "计算最佳机会中...",
        "bubble_no_opps" to "未找到合适的市场机会。",
        "bubble_search" to "市场搜索...",
        "bubble_hold_move" to "长按移动",
        "bubble_exit" to "退出",
        "bubble_kauf" to "买入:",
        "bubble_verkauf" to "卖出:",
        "bubble_buy_price" to "买入单价 (银币)",
        "bubble_sell_price" to "卖出单价 (银币)",
        "bubble_bought_amount" to "已买数量",
        "bubble_spent" to "支出",
        "bubble_earned" to "收入",
        "bubble_profit_loss" to "利润/亏损",
        "bubble_include_brecilien" to "将 Brecilien 纳入路线",
        "bubble_compact_mode" to "📱 紧凑悬浮窗模式",
        "bubble_compact_desc" to "缩小悬浮窗尺寸、边距与字体大小",
        "bubble_opacity" to "👁️ 悬浮窗不透明度",
        "bubble_scale" to "🔍 悬浮窗缩放比例",
        "tab_crafting" to "🛠️ 制造指南",
        "tab_island" to "🏝️ 岛屿指南",
        "crafting_search" to "搜索要制造的物品...",
        "crafting_req_ingredients" to "所需资源与最低价格市场:",
        "cheapest_at" to "最低价购买",

        // Cities
        "city_caerleon" to "卡尔利昂",
        "city_brecilien" to "布雷西林",
        "city_arthurs_rest" to "亚瑟的休息地",
        "city_merlyns_rest" to "梅林的休息地",
        "city_morganas_rest" to "莫甘娜的休息地",
        "city_bridgewatch" to "桥区",
        "city_martlock" to "马特洛克",
        "city_lymhurst" to "绿荫",
        "city_fort_sterling" to "雪山",
        "city_thetford" to "紫城",
        "city_cairn_drain" to "Cairn Drain",
        "red_zone" to "🔴 红区",
        "black_zone" to "⚫ 黑区"
    )

    fun getString(key: String, langCode: String): String {
        val baseDe = deMap[key] ?: key
        if (langCode.equals("DE", ignoreCase = true)) return baseDe

        val staticTrans = when (langCode.uppercase()) {
            "EN" -> enMap[key]
            "ZH" -> zhMap[key]
            else -> null
        }
        return staticTrans ?: enMap[key] ?: baseDe
    }

    fun getCityTranslation(city: String, langCode: String): String {
        val key = "city_${city.lowercase().replace(" ", "_").replace("'", "")}"
        val trans = getString(key, langCode)
        return if (trans == key) city else trans
    }
}
